# ----------------------------------- Spring Setting --------------------------------------
spring:
  application:
    name: simulator
# ----------------------------------- Server Setting ------------------------------
server:
  port: 8082
